# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python pytest

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#         os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        python-version: [3.7, 3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: conda info
      shell: bash -l {0}
      run: conda info
    - name: Install dependencies
      shell: bash -l {0}
      run: |
        python -m pip install --upgrade pip
        pip install -q pytest pytest-cov==2.4.0  python-coveralls  codacy-coverage
        pip install -q git+https://github.com/DataCanvasIO/Hypernets
        pip install -q -r requirements.txt
        pip list
    - name: conda list
      shell: bash -l {0}
      run: conda list
    - name: Test with pytest
      shell: bash -l {0}
      run: |
        export TSB_CONDA_HOME=/usr/share/miniconda
        pytest --cov=tsbenchmark --durations=30
